domain_path: C:\Users\820759\pi_serial\vitis_workspace\zybo_platform\zynq_fsbl\zynq_fsbl_bsp
app_src_dir: C:\AMDDesignTools\2025.2\Vitis\data\embeddedsw\lib\sw_apps\zynq_fsbl
template: zynq_fsbl
lang: c
